services:
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgresql://ttvk:ttvk@postgres/ttvk?sslmode=disable
      PORT: 8080
    depends_on:
      - postgres

  front:
    container_name: front
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  pinger:
    container_name: pinger
    environment:
      API_URL: http://back:8080/api/address/
    build:
      context: ./pinger
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - back

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ttvk
      POSTGRES_PASSWORD: ttvk
      POSTGRES_DB: ttvk
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: